version: "3.4"

services:
  trester:
    image: traefik-tester:0.1.1
    networks:
      - public-net
    deploy:
      replicas: 4
      labels:
        - "traefik.enable=true"
        - "traefik.port=8989"
        - "traefik.tags=public-net"
        - "traefik.docker.network=public-net"
        - "traefik.frontend.rule=PathPrefixStrip:/test"
        - traefik.webservice.frontend.entryPoints=http,https

networks:
  public-net:
    external: true
